/**
 * Icon registry — the single icon language for this app.
 *
 * Rules:
 *  - lucide-react is the primary icon library (matches the Chronos design
 *    system — no Font Awesome, no icon-library duplication).
 *  - One semantic concept maps to exactly one glyph. "maintenance" must look
 *    identical in the sidebar, in a table cell and on a card.
 *  - Only the icons listed here are imported, so the bundle stays scoped and tree-shakeable.
 *
 * Add a concept here rather than importing a lucide icon directly at a call
 * site — the registry is what keeps the language consistent.
 */
import {
  // navigation / app sections
  LayoutDashboard,
  Car,
  Network,
  Boxes,
  BookMarked,
  FlaskConical,
  TrendingUp,
  TrendingDown,
  GitCompare,
  Dice5,
  CalendarCheck,
  Activity,
  HeartPulse,
  Trophy,
  FileText,
  Leaf,
  Plug,
  BookOpen,
  SlidersHorizontal,
  Home,
  User,
  // actions
  Play,
  LogOut,
  Menu,
  Plus,
  Minus,
  Trash2,
  Archive,
  SquarePen,
  Check,
  X,
  Search,
  Filter,
  RefreshCw,
  Eye,
  EyeOff,
  Star,
  Ellipsis,
  EllipsisVertical,
  GripVertical,
  Download,
  Upload,
  ExternalLink,
  Link,
  PanelLeft,
  // direction
  ChevronDown,
  ChevronUp,
  ChevronLeft,
  ChevronRight,
  ArrowLeft,
  ArrowRight,
  ArrowDown,
  ArrowUp,
  Circle,
  CircleDot,
  // system / status
  Lock,
  Mail,
  ShieldCheck,
  ShieldOff,
  TriangleAlert,
  Info,
  CircleCheck,
  CircleX,
  CircleHelp,
  Clock,
  Users,
  Building2,
  Database,
  Server,
  Cpu,
  RadioTower,
  GitBranch,
  Layers,
  Package,
  Zap,
  Bell,
  Calendar,
  Maximize,
  Target,
  ZoomIn,
  ZoomOut,
  Palette,
  Sparkles,
  Cloud,
  // automotive / fleet
  Wrench,
  Fuel,
  Gauge,
  Droplet,
  Recycle,
  TrainFront,
  Route,
  MapPin,
  // data
  LineChart,
  BarChart3,
  PieChart,
  Calculator,
  Percent,
  PiggyBank,
  Table,
  ArrowUpDown,
  DollarSign,
  type LucideIcon,
} from "lucide-react";

export const icons = {
  /* ---- navigation / app sections ---- */
  dashboard: LayoutDashboard,
  vehicle: Car,
  vehicles: Car,
  hierarchy: Network,
  bom: Boxes,
  library: BookMarked,
  simulation: FlaskConical,
  forecasting: TrendingUp,
  scenarios: GitCompare,
  monteCarlo: Dice5,
  schedule: CalendarCheck,
  reliability: Activity,
  assetHealth: HeartPulse,
  benchmark: Trophy,
  document: FileText,
  documents: FileText,
  sustainability: Leaf,
  integrations: Plug,
  glossary: BookOpen,
  settings: SlidersHorizontal,
  home: Home,
  user: User,

  /* ---- actions ---- */
  play: Play,
  logout: LogOut,
  menu: Menu,
  add: Plus,
  minus: Minus,
  subtract: Minus,
  delete: Trash2,
  archive: Archive,
  edit: SquarePen,
  check: Check,
  close: X,
  search: Search,
  filter: Filter,
  refresh: RefreshCw,
  show: Eye,
  hide: EyeOff,
  star: Star,
  more: Ellipsis,
  moreVertical: EllipsisVertical,
  drag: GripVertical,
  download: Download,
  upload: Upload,
  link: Link,
  externalLink: ExternalLink,
  panelLeft: PanelLeft,

  /* ---- direction ---- */
  chevronDown: ChevronDown,
  chevronUp: ChevronUp,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  arrowLeft: ArrowLeft,
  arrowRight: ArrowRight,
  arrowDown: ArrowDown,
  arrowUp: ArrowUp,
  circle: Circle,
  circleDot: CircleDot,

  /* ---- system / status ---- */
  lock: Lock,
  mail: Mail,
  warrantyActive: ShieldCheck,
  warrantyExpired: ShieldOff,
  warning: TriangleAlert,
  alerts: TriangleAlert,
  info: Info,
  success: CircleCheck,
  error: CircleX,
  help: CircleHelp,
  clock: Clock,
  users: Users,
  organization: Building2,
  database: Database,
  server: Server,
  cpu: Cpu,
  signal: RadioTower,
  branch: GitBranch,
  layers: Layers,
  package: Package,
  power: Zap,
  notification: Bell,
  calendar: Calendar,
  fullscreen: Maximize,
  target: Target,
  zoomIn: ZoomIn,
  zoomOut: ZoomOut,
  palette: Palette,
  sparkle: Sparkles,
  cloud: Cloud,

  /* ---- automotive / fleet ---- */
  maintenance: Wrench,
  tools: Wrench,
  repair: Wrench,
  fuel: Fuel,
  gauge: Gauge,
  fluid: Droplet,
  recycle: Recycle,
  locomotive: TrainFront,
  route: Route,
  road: Route,
  map: MapPin,
  location: MapPin,

  /* ---- data ---- */
  chart: LineChart,
  chartBar: BarChart3,
  chartPie: PieChart,
  calculator: Calculator,
  percent: Percent,
  savings: PiggyBank,
  table: Table,
  cost: DollarSign,
  sort: ArrowUpDown,
  trend: TrendingUp,
  trendUp: TrendingUp,
  trendDown: TrendingDown,
} as const satisfies Record<string, LucideIcon>;

export type IconName = keyof typeof icons;
